// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs4399VCN9_9Btgop9hoLhq6IMt_xmksY',
    appId: '1:835328440284:web:612b4b26b1f285ed2c8119',
    messagingSenderId: '835328440284',
    projectId: 'bustime-senegal-2026-dc2c9',
    authDomain: 'bustime-senegal-2026-dc2c9.firebaseapp.com',
    storageBucket: 'bustime-senegal-2026-dc2c9.firebasestorage.app',
    measurementId: 'G-ZHY3QDGVYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUCoSV8HLQgFDX5_2kNCA0-2v7B5HeEj0',
    appId: '1:835328440284:android:d4f894f0666a582c2c8119',
    messagingSenderId: '835328440284',
    projectId: 'bustime-senegal-2026-dc2c9',
    storageBucket: 'bustime-senegal-2026-dc2c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnwC7xV8V3uMRsqq85ZMnzRbZKU-0cUkk',
    appId: '1:835328440284:ios:7a0a98a714e63d0b2c8119',
    messagingSenderId: '835328440284',
    projectId: 'bustime-senegal-2026-dc2c9',
    storageBucket: 'bustime-senegal-2026-dc2c9.firebasestorage.app',
    iosBundleId: 'com.example.senebusLive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnwC7xV8V3uMRsqq85ZMnzRbZKU-0cUkk',
    appId: '1:835328440284:ios:7a0a98a714e63d0b2c8119',
    messagingSenderId: '835328440284',
    projectId: 'bustime-senegal-2026-dc2c9',
    storageBucket: 'bustime-senegal-2026-dc2c9.firebasestorage.app',
    iosBundleId: 'com.example.senebusLive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs4399VCN9_9Btgop9hoLhq6IMt_xmksY',
    appId: '1:835328440284:web:55ea5486d28162702c8119',
    messagingSenderId: '835328440284',
    projectId: 'bustime-senegal-2026-dc2c9',
    authDomain: 'bustime-senegal-2026-dc2c9.firebaseapp.com',
    storageBucket: 'bustime-senegal-2026-dc2c9.firebasestorage.app',
    measurementId: 'G-TE1DSPQS8Z',
  );
}
